general:
    logfile: /var/log/sensible/sensible.log
    loglevel: error
    scriptlocation: /etc/sensible/scripts/
mqtt:
    hostname: mqtt-broker
    port: "1883"
    username: "hassio"
    password: "hassio"
    clientid: sensible_mqtt_client
discovery:
    devicename: sensible-homeassistant
    prefix: homeassistant
api:
    enabled: false
plugins:
    - name: Heartbeat
      kind: internal
      sensorid: heartbeat
      script: ""
      unitofmeasurement: ""
      icon: mdi:wrench-check
    - name: Boot Time
      kind: script
      sensorid: boot_time
      script: boot_time.sh
      unitofmeasurement: ""
      icon: mdi:clock
    - name: System Time
      kind: internal
      sensorid: system_time
      script: ""
      unitofmeasurement: ""
      icon: mdi:clock
    - name: Root Disk Used
      kind: script
      sensorid: root_used
      script: root_used.sh
      unitofmeasurement: GB
      icon: mdi:harddisk
    - name: Root Disk Free
      kind: script
      sensorid: root_free
      script: root_free.sh
      unitofmeasurement: GB
      icon: mdi:harddisk
    - name: CPU Temperature
      kind: script
      sensorid: cpu_temp
      script: cpu_temp.sh
      unitofmeasurement: C
      icon: mdi:temperature-celsius
    - name: CPU Load
      kind: script
      sensorid: cpu_load
      script: cpu_load.sh
      unitofmeasurement: "%"
      icon: mdi:cpu-64-bit
    - name: Host IP Address
      kind: script
      sensorid: ip_address
      script: ip_address.sh
      unitofmeasurement: ""
      icon: mdi:network
    - name: Hostname
      kind: script
      sensorid: hostname
      script: hostname.sh
      unitofmeasurement: ""
      icon: mdi:network
    - name: Platform
      kind: script
      sensorid: platform
      script: platform.sh
      unitofmeasurement: ""
      icon: mdi:wrench-check
    - name: Mem Total
      kind: script
      sensorid: mem_total
      script: total_mem.sh
      unitofmeasurement: GB
      icon: mdi:memory
    - name: Mem Free
      kind: script
      sensorid: mem_free
      script: free_mem.sh
      unitofmeasurement: GB
      icon: mdi:memory
    - name: Mem Used
      kind: script
      sensorid: mem_used
      script: used_mem.sh
      unitofmeasurement: GB
      icon: mdi:memory
    - name: Mem Load
      kind: script
      sensorid: mem_load
      script: mem_load.sh
      unitofmeasurement: "%"
      icon: mdi:memory
